packages:
  - projects/*

catalog:
  '@somni/eslint-config': https://gitpkg.vercel.app/somnisomni/webdev-common/packages/eslint-config?main
  '@types/eslint': ^9.6.1
  '@types/node': ^24.1.0
  eslint: ^9.32.0
  typescript: ^5.8.3
  vite: ^7.0.6

ignoredBuiltDependencies:
  - '@tailwindcss/oxide'
  - es5-ext
  - sharp
  - unrs-resolver

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - esbuild
  - prisma
  - workerd
