packages:
  - projects/*

catalog:
  '@somni/eslint-config': https://github.com/somnisomni/webdev-common.git#path:/packages/eslint-config
  '@types/eslint': ^9.6.1
  '@types/node': ^24.10.1
  eslint: ^9.39.1
  typescript: ^5.9.3
  vite: ^7.2.6

ignoredBuiltDependencies:
  - '@tailwindcss/oxide'
  - es5-ext
  - sharp
  - unrs-resolver

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - esbuild
  - prisma
  - workerd
